---
language: node_js
node_js:
  - 6.9.2

sudo: false

dist: trusty
addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn run lint
  - yarn test

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
