---
language: node_js
node_js:
  - 6.9.2

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install

script:
  # - npm run lint
  # - npm test

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
