---
language: node_js
node_js:
  - 5.11

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install
  - bower install

script:
  - npm run lint
  - npm test

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
