---
language: node_js
node_js:
  - 10.4.1

sudo: false

dist: trusty
addons:
  chrome: stable

cache:
  npm: true

install:
  - npm install -g npm@6.1.0
  - npm install

script:
  - ./scripts/ci-check.sh

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
