---
language: node_js
node_js:
  - 8.10

sudo: false

dist: trusty
addons:
  chrome: stable

cache:
  npm: true

install:
  - npm install -g npm@5.6
  - npm install

script:
  - npm run lint
  - npm test

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
