---
language: node_js
node_js:
  - 5.11

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install
  - bower install

script:
  - npm run lint
  # NOTE: This line must be disabled in the boilerplate code because it fails
  # even if we don’t have any tests (it needs at least one passing test to
  # exit successfully). We need to uncomment it when we add tests.
  # - npm test

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
