---
language: node_js
node_js:
  - 10.15.1

dist: trusty
addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@6.8.0
  - npm ci

script:
  - ./scripts/ci-check.sh
