---
language: node_js
node_js:
  - 6.9.2

sudo: false

dist: trusty
addons:
  chrome: stable

cache:
  npm: true

install:
  - npm install

script:
  # - npm run lint
  # - npm test

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
