---
language: node_js
node_js:
  - 10.14.1

dist: trusty
addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm install -g npm@6.4.1
  - npm install

script:
  - ./scripts/ci-check.sh
